import { createSlice, PayloadAction } from "@reduxjs/toolkit";
import Country from "src/types/Country";

// Define the structure of ContinentData
interface ContinentData {
    name: string;
    countries: Country[];
    count: number;
    image: string;
}

// Define the structure of the state
interface ContinentState {
    continents: ContinentData[];
}

// Initialize the state with an empty array of continents
const initialState: ContinentState = {
    continents: [],
};

// Create a slice for continent-related state management
const continentSlice = createSlice({
    name: "continent",
    initialState,
    reducers: {
        // Action to set the list of continents
        setContinents: (state, action: PayloadAction<ContinentData[]>) => {
            state.continents = action.payload;
        },
        // Action to update a specific continent or add it if it doesn't exist
        updateContinent: (state, action: PayloadAction<ContinentData>) => {
            const index = state.continents.findIndex(c => c.name === action.payload.name);
            if (index !== -1) {
                state.continents[index] = action.payload;
            } else {
                state.continents.push(action.payload);
            }
        },
    }
});

// Export the actions generated by createSlice
export const { setContinents, updateContinent } = continentSlice.actions;

// Export the reducer to be used in the store
export default continentSlice.reducer;