import { createSlice, PayloadAction } from '@reduxjs/toolkit';
import Destination from 'src/types/Destination';

// Define the initial state of the destinations slice
interface DestinationsState {
  currentDestination: Destination | null;
  destinations: Destination[];
  allDestinations: Destination[];
  featuredDestinations: Destination[];
  totalDestinations: number;
  loading: boolean;
  error: string | null;
}

const initialState: DestinationsState = {
  currentDestination: null,
  destinations: [],
  allDestinations: [],
  featuredDestinations: [],
  totalDestinations: 0,
  loading: false,
  error: null,
};

// Create the destinations slice
const destinationsSlice = createSlice({
  name: 'destinations',
  initialState,
  reducers: {
    // Set the current destination
    setCurrentDestination: (state, action: PayloadAction<Destination | null>) => {
      state.currentDestination = action.payload;
    },
    // Set the list of destinations
    setDestinations: (state, action: PayloadAction<Destination[]>) => {
      state.destinations = action.payload;
    },
    // Set the list of all destinations
    setAllDestinations: (state, action: PayloadAction<Destination[]>) => {
      state.allDestinations = action.payload;
    },
    // Set the list of featured destinations
    setFeaturedDestinations: (state, action: PayloadAction<Destination[]>) => {
      state.featuredDestinations = action.payload;
    },
    // Set the total number of destinations
    setTotalDestinations: (state, action: PayloadAction<number>) => {
      state.totalDestinations = action.payload;
    },
    // Set the loading state
    setLoading: (state, action: PayloadAction<boolean>) => {
      state.loading = action.payload;
    },
    // Set the error message
    setError: (state, action: PayloadAction<string | null>) => {
      state.error = action.payload;
    },
  },
});

// Export the actions generated by createSlice
export const {
  setCurrentDestination,
  setDestinations,
  setAllDestinations,
  setFeaturedDestinations,
  setTotalDestinations,
  setLoading,
  setError,
} = destinationsSlice.actions;

// Export the reducer to be used in the store
export default destinationsSlice.reducer;
